### ISSUE TITLE
access transformer no longer applied as of 2.6.1.1

### ISSUE THREAD

**Issue by srs-bsns** [Tomson124/SimplyJetpacks2#10]
In 178f976d9e7cc119ac445975996b67697d8d5c8e you renamed your access transformer file from `accesstransformer.cfg` to `simplyjetpacks_at.cfg`, and as a result it is no longer loaded and applied. In order for FML to load the file it must be named `accesstransformer.cfg`.
You likely didn't notice this in dev because of the change made in `build.gradle` to reflect the filename change:
```groovy
    accessTransformer = file('src/main/resources/META-INF/simplyjetpacks_at.cfg')
```
This, however, only applies to a dev environment.

**Comment by tomheaton** [comment]
Thank you !
