### ISSUE TITLE
Parsing error loading built-in advancement simplyjetpacks....

### ISSUE THREAD

**Issue by IITFA** [Tomson124/SimplyJetpacks2#14]
https://pastebin.com/raw/TwzA9JT4

Spotted this in the console, so reporting it.

**Comment by Tomson124** [comment]
Could you please report more information on your setup? Like a list of mods installed with the corresponding versions. Which Minecraft version? Judging from the log you didn't experience a crash, so what were you doing at or shortly before the moment the error appeared?

**Comment by tomheaton** [comment]
We can look into removing the log errors, but this is completely normal. Thank you for the report.
