### ISSUE TITLE
Config buttons are grayed out

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Tomson124/SimplyJetpacks2#16]
Forge: 14.23.5.2847
Simply Jetpacks 2: 2.2.16.1

Some of the config buttons on the ingame config are grayed out and unable to be pressed. This is the case for the Item Settings Category and the Integration Settings Category
![config3](https://user-images.githubusercontent.com/31759736/93949701-2e781f00-fcf6-11ea-9d59-a5b0ce4399ab.PNG)

**Comment by tomheaton** [comment]
You cannot edit these config values while in a loaded world, as a game restart is required. You can edit these from the main menu and then restart the game to apply them.

**Comment by ALongStringOfNumbers** [comment]
If this is the case, then why not annotate the config fields with `@Config.RequiresMCRestart` or `@Config.RequiresWorldRestart` ? This will allow the values to be changed in game, but will display a warning message when the user exits the Mod Config screen informing them that they need to restart for the changes to occur.
