### ISSUE TITLE
[1.12.2] (Suggestion) Option to disable automatic advancements?

### ISSUE THREAD

**Issue by luke-bravenboer** [Tomson124/SimplyJetpacks2#17]
(Minecraft version 1.12.2)

Regarding version **2.2.16** of Simply Jetpacks... (many thanks for all the work you put into this update, by the way!)

I'm getting a brief spam of unwanted achievements/advancements from this mod every time I create a new world now- the more integration modules enabled, the worse it is, as there's an achievement for every single module, as well as another that's just saying I've installed the mod.

In the interest of not confusing/overwhelming new players with anything superfluous, any chance these could be disabled via config option?

**Comment by xJon** [comment]
Would be a great feature.

**Comment by rlnt** [comment]
I do also second this. Please make this an option. It's really annoying.

**Comment by Kangy1103** [comment]
Any updates on this please?

**Comment by luke-bravenboer** [comment]
> Any updates on this please?

Not the mod author, just wanted to remind anyone that dev effort for this mod seems to be focusing on MC 1.16 now (as is the case with most mod developers); but if you really want an immediate fix, you could use the [previous version of Simply Jetpacks 2](https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2/files/3017440) instead :)

**Comment by Kangy1103** [comment]
> > Any updates on this please?
> 
> Not the mod author, just wanted to remind anyone that dev effort for this mod seems to be focusing on MC 1.16 now (as is the case with most mod developers); but if you really want an immediate fix, you could use the [previous version of Simply Jetpacks 2](https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2/files/3017440) instead :)

It's nothing I can't deal with for now :) just creating a modpack so would be nice to not have them. When it's closer to release I will probably drop a version if there hasn't been an update

**Comment by IchigoGames** [comment]
Yes :) ^

**Comment by xJon** [comment]
Even with the config value changed, I'm still getting this when first creating a world:
![image](https://user-images.githubusercontent.com/8945347/101537442-28641700-39a4-11eb-81b5-fc1998390a64.png)
![image](https://user-images.githubusercontent.com/8945347/101537412-1bdfbe80-39a4-11eb-8925-a8a4842d9dc5.png)

**Comment by IchigoGames** [comment]
i dont mine that one just get annoyed at all the ones you get if you have other mods

**Comment by tomheaton** [comment]
I have just fixed this, will push tonight! :D

**Comment by xJon** [comment]
> I have just fixed this, will push tonight! :D

Thank you! I just created a custom filter using [ChatFlow](https://www.curseforge.com/minecraft/mc-mods/chatflow), but it is probably better to have it fixed from the mod's end.

**Comment by IchigoGames** [comment]
so are there any plans on doing this update

**Comment by IchigoGames** [comment]
oh i see you did update.....for 1.12

**Comment by IchigoGames** [comment]
can we get this but for 1.16.3 or 1.16.4

**Comment by IchigoGames** [comment]
or is it 1.12 what does it mean by gamer version forge ?? 
![image](https://user-images.githubusercontent.com/11888162/101936747-90824b00-3ba6-11eb-80a9-b4e0abc76074.png)

**Comment by Macleykun** [comment]
> I have just fixed this, will push tonight! :D

Heya, sorry to revive this old thread but was this fix pushed and published?
