### ISSUE TITLE
no thrusters?

### ISSUE THREAD

**Issue by Fisheiyy** [Tomson124/SimplyJetpacks2#19]
im on 1.12.2 and I cannot see the leadstone thrusters and such I have enderio and all the thermal mods

**Comment by Tomson124** [comment]
Please always tell us the version of SJ2 you have, too.
But in this case: Did you enable the integration for the other mods in the config file?

**Comment by Fisheiyy** [comment]
> Please always tell us the version of SJ2 you have, too.
> But in this case: Did you enable the integration for the other mods in the config file?

everything but vanilla integration is enabled and im using SimplyJetpacks2-1.12.2-2.2.16.1

**Comment by Tomson124** [comment]
So which items are missing? All of them? Which other mods are you using and which version of the other mods, maybe provide the log file.

**Comment by Fisheiyy** [comment]
> So which items are missing? All of them? Which other mods are you using and which version of the other mods, maybe provide the log file.

im not getting a crash log or anything just ingame the leadstone thrusters and such dont show in jei when I search for them, because im trying to use crafttweaker to change the recipe of the leadstone jetpack

edit: if anything I can use crafttweaker to give it a recipe but i dont remember the default recipe

**Comment by Tomson124** [comment]
Wait a minute, so you do not get any of the simplyjetpacks items or just not the Leadstone related ones? Did you get them before messing with crafttweaker? Maybe this is something we better should discuss on discord rather than here.

**Comment by Tomson124** [comment]
Did you get it working?

**Comment by Fisheiyy** [comment]
> Did you get it working?

nope

**Comment by pat2rome** [comment]
I know this isn't too helpful a year later, but here's what he means: only the Fluxed Thruster shows up directly in JEI. To look up the reciple for any other tier of thruster, you have to search for the jetpack that uses it as a component and then look up the recipe from its appearance in that recipe. Thermal Expansion has config options to control what tiers of items show up in JEI, and I suggest something like that be done here too.
