### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by IchigoGames** [Tomson124/SimplyJetpacks2#20]
add a option in  the config to disable achievements or just the 4-5 that broadcasts to server Every time some one joins.

![image_2020-11-14_153611](https://user-images.githubusercontent.com/11888162/99157526-1f2aa780-268f-11eb-98f2-c580fdb7461a.png) ingore the rat one all of these are from this mod

**Comment by IchigoGames** [comment]
i do not mine the first one the completed challenge but the rest is just to much

**Comment by tomheaton** [comment]
duplicate of #17, will be fixed in next update.
