### ISSUE TITLE
Can't apply Particle Customizer to Ultimate Jetpack

### ISSUE THREAD

**Issue by Shadowfire86** [Tomson124/SimplyJetpacks2#24]
Playing on Direwolf20 1.16 pack, and I have a Mekanism branch Ultimate Armored Jetpack. For the life of me I either can't apply the Particle Customizer (None) to it, or I'm missing something. I've tried looking through the UI, Shift, Alt, Ctrl Right Clicking, and placing them in a crafting table together. None of these work.

**Comment by tomheaton** [comment]
For now, the particle customizers are still in progress.
