### ISSUE TITLE
No recipes for Thermal Jetpacks

### ISSUE THREAD

**Issue by Sunekaer** [Tomson124/SimplyJetpacks2#26]
https://paste.sunekaer.com/azoxosotiw.bash

![image](https://user-images.githubusercontent.com/18720460/103569486-aa722d80-4ec7-11eb-8ee3-4ee3b8d8deff.png)

**Comment by tomheaton** [comment]
Still waiting on Thermal to add some more items to make the recipes work, just popped them in there for people to see what is coming :D
