### ISSUE TITLE
[1.12.2] Updating to 2.2.18.1 causes existing jetpacks to change

### ISSUE THREAD

**Issue by xJon** [Tomson124/SimplyJetpacks2#34]
This was reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/605.
> After updating to the latest version of the modpack v1.3.1 from v1.3.0 when logging into my singleplayer world, my Armored Hardened Jetpack was replaced by a Dark Soularium Jetplate.

Any idea what caused this?

**Comment by Tomson124** [comment]
Sorry for really late resonse. Did this happen when updating to a even newer version, too? E.g. 2.19.x?
After a quick look it could have been related to changes in the recipe and Item "creation" in 2.18,x.

**Comment by mdrusto** [comment]
It happened to me as well when updating to 2.20.0, but that was all the way from 2.14.67.

**Comment by tomheaton** [comment]
This is due to the meta tags changing if an item is registered either before or after another item that is different to the previous version. Enjoy the free upgrade. 🌮
