### ISSUE TITLE
1.16.5 Cannot see ThermalExapansion Jetpacks/Thrusters recipes, neither craft them

### ISSUE THREAD

**Issue by Vulcanos7** [Tomson124/SimplyJetpacks2#54]
I can see the recipe in the jei, but when i click on them to see the crafting grid recipe, it only shows the armored to non armored recipe, not the normal jetpack recipe.
I don't if this is a bug or a conflict, the other recipes works just fine(Vanilla, Mekanism and Immersive Engineering)
I cant seen to be able to craft the recipe as well, tried in creative but seems that, either i don't know the recipe or is not working.
I'm using the SJ2 v2.6.7.1.
(sorry for my english, that's not my language)

**Comment by tomheaton** [comment]
Still waiting on Thermal to add some more items to make the recipes work.

**Comment by Vulcanos7** [comment]
Oh, ok, thanks
