### ISSUE TITLE
Server crashes due to Simply Jetpacks 2

### ISSUE THREAD

**Issue by RupertDeRuyver** [Tomson124/SimplyJetpacks2#57]
The server crashes due to Simply Jetpacks 2. When I remove the mod, everything works perfectly. The server log and crash log are attached. I use version 2.2.20, but older versions don't work either.
[crash-2021-08-03_15.31.38-server.txt](https://github.com/Tomson124/SimplyJetpacks2/files/6924410/crash-2021-08-03_15.31.38-server.txt)
[latest.log](https://github.com/Tomson124/SimplyJetpacks2/files/6924411/latest.log)

**Comment by tomheaton** [comment]
fairly sure this has something to do with stacks of some sort, not too sure at the moment.

**Comment by tomheaton** [comment]
The fix for this is mentioned here now, hope this helps 🙂 
https://github.com/Tomson124/SimplyJetpacks2/wiki/Common-Issues#server-crashes
