### ISSUE TITLE
[1.17.1] Server "crashes" / datapack failure when booting up.

### ISSUE THREAD

**Issue by Gbergz** [Tomson124/SimplyJetpacks2#58]
Title^

When SimplyJetpacks2 is on a server it crashes or a datapack failure while trying to boot it.

**Minecraft:** 1.17.1
**Forge**: 37.0.27
**SimplyJetpacks2:** 1.17.1-2.7.1.1

**Crash-Report / Logs:** https://gist.github.com/Gbergz/ad919ba74e0c68f8f628ee5a1f731a37

**Comment by MrScautHD** [comment]
i can confirm this bug (i have the same one)

**Comment by TigerWalts** [comment]
This bug is still present in 2.7.2.1

**Minecraft**: 1.17.1
**Forge**: 37.1.1
**SimplyJetpacks2**: 1.17.1-2.7.121

**Crash-Report**: N/A
**Log**: https://gist.github.com/TigerWalts/646f59f2a26664fc139828f223450171
