### ISSUE TITLE
[1.16] Advancement keeps showing even when enableJoinAdvancements is false

### ISSUE THREAD

**Issue by jinkhya** [Tomson124/SimplyJetpacks2#59]
Hello,
I've turned off enableJoinAdvancements but we still get it.
Thanks in advance,
Jin

**Comment by jinkhya** [comment]
actually I see a new version came out 4 hours ago, does that version fix that? (didn't see anything about it in changelog)

**Comment by tomheaton** [comment]
the fix to this is still in the pipeline, it will be available in the next update

**Comment by jinkhya** [comment]
okidoke thanks for the feedback !
