### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by frank89722** [Tomson124/SimplyJetpacks2#60]
After update to SimplyJetpacks2-1.16.5-2.6.9.1, server crash on startup

Crash report: https://gist.github.com/frank89722/0f61113b924d0152a007bc43f41c443e

**Comment by Boboer324** [comment]
Same [crash-2021-08-16_02.08.03-fml.txt](https://github.com/Tomson124/SimplyJetpacks2/files/6989152/crash-2021-08-16_02.08.03-fml.txt)
