### ISSUE TITLE
1.16.5| Simply Jetpack 2 Wont Start on server

### ISSUE THREAD

**Issue by epicyeeto** [Tomson124/SimplyJetpacks2#62]
I saw an error code saying Failed to create mod instance. ModID: simplyjetpacks, class stormedpanda.simplyjetpacks.SimplyJetpacks

Version Of Forge: 36.2.2
version of mod:  SimplyJetpacks2-1.16.5-2.6.9.1.jar

[crash-2021-08-18_00.44.30-fml.txt](https://github.com/Tomson124/SimplyJetpacks2/files/7003764/crash-2021-08-18_00.44.30-fml.txt)

i think it is because I have a lot of client side mods but Idk what doing it

**Comment by tomheaton** [comment]
please update to version 1.16.5-2.6.10.1, this should have fixed the problem. 👍

**Comment by Gbergz** [comment]
Latest release for 1.17.1; v2.7.2.1 https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2/files/3448994

still doesn't boot on servers. Datapack failure when booting up. (Clean server files with only Simply jetpacks 2) on forge 37.0.61
