### ISSUE TITLE
Simply Jetpacks 2 and Mohist

### ISSUE THREAD

**Issue by BirnenLaser** [Tomson124/SimplyJetpacks2#67]
Hello, trying to run the "Divine Journey 2" modpack with Mohist as server file. Getting this crashlog:
https://pastebin.com/Uf6CtcF6

I do see that this is probably a modpack specific issue but the author couldnt help me, so here i am.

**Comment by tomheaton** [comment]
I feel like I have seen an issue like this before, unfortunately there is so little information that I am not able to do much. Is there any more information you can give? Like when this crash happens etc?

**Comment by aspiringLich** [comment]
this crash happens on startup, i am relatively certain the pack hasn't had much done to it besides installing mohist, the crash happens consistently on startup sometime before the server generates the world file. The server doesnt actually crash though, it makes a crash report, but it just stalls, console freezes cpu usage drops to nothing, 

here are the last things console spits out before it stalls and spams error messages:
https://pastebin.com/GVf18Xnb

here is the latest.log:
[latest.log](https://github.com/Tomson124/SimplyJetpacks2/files/7080564/latest.log)

the stall / crash seems relatively consistent happening the same way every time.

We have tested DJ2 without mohist and it seems to work fine, we also have MC:E running successfully with mohist and that has simply jetpacks 2 too.

**Comment by LordFusion** [comment]
I have received the exact same error when running an Omnifactory server with Mohist. 

The workaround is to add `-noverify` to your startup script, as such: 
`java -noverify -jar mohist-<mcversion>-<buildnumber>-server.jar` 

<details>
<summary> My own crash/server details: </summary>

Simply Jetpacks 2 Version: 2.2.14.67
Mohist Version: 1.12-248
Omnifactory Pack Version: 1.2.2
Crash Report: https://pastebin.com/znDVXLYh
</details>

**Comment by aspiringLich** [comment]
hm, ill try that and get back to you if it works

**Comment by aspiringLich** [comment]
thank you! that seemed to work

**Comment by tomheaton** [comment]
thank you LordFusion. I have created a page in the Wiki pertaining to this issue which provides your fix. Hopefully this helps others. 😄
