### ISSUE TITLE
[1.16.5] No recipe for Glowstone Elevation and Cryotheum Coolant units (full versions)

### ISSUE THREAD

**Issue by bochen415** [Tomson124/SimplyJetpacks2#80]
I wanted to make the Flux-Infused JetPlate, those two units from the title are needed to craft it. Is the JetPlate work in progress?
I'm probably doing something wrong here.

SimplyJetpacks2-1.16.5-2.6.12.1
thermal_expansion-1.16.5-1.4.2.4
thermal_foundation-1.16.5-1.4.3.10
cofh_core-1.16.5-1.4.2.9
and a bunch of other mods.

MinecraftForge 36.2.21

**Comment by tomheaton** [comment]
The Glowstone Elevation unit should be craftable as Liquid Glowstone does exist in the latest version of CoFH mods. As Liquid Cryotheum hasn't been added yet there is not recipe for the Cryotheum Coolant unit

**Comment by bochen415** [comment]
Requesting reopening, I got info that cryo is probably not coming back in liquid form.
Glowstone Elevation units are still not craftable even with Energized Glowstone present.

**Comment by awesomebossdj7** [comment]
also happens on 1.18.2
