### ISSUE TITLE
Valentines Day off by one Error

### ISSUE THREAD

**Issue by Complexicon** [Tomson124/SimplyJetpacks2#81]
I noticed heart particles today ingame but today isn't valentines day

see [here](https://github.com/Tomson124/SimplyJetpacks2/blob/694b7bbf58778a2d4303d030ee6b79e1f51263c9/src/main/java/tonius/simplyjetpacks/client/handler/ClientTickHandler.java#L118)

**Comment by tomheaton** [comment]
fixed in dev
